# Generated by Django 6.1.1 on 2026-09-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', '映画'), ('book', '本')], max_length=10, verbose_name='メディア')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('reason', models.TextField(verbose_name='おすすめ理由・あらすじ')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='画像URL')),
                ('tags', models.CharField(help_text='カンマ区切りでタグを入力（例: 疲れた, 癒やされたい）', max_length=200, verbose_name='タグ')),
            ],
        ),
    ]
