# Generated by Django 6.1.1 on 2026-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', '映画'), ('book', '本')], max_length=10, verbose_name='メディア')),
                ('title', models.CharField(max_length=200, verbose_name='好きな作品・おすすめ作品')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント・理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
    ]
