name: Keep Render Awake

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ping Render
        run: curl -f https://recommend-app-uo5g.onrender.com/